### ISSUE TITLE
allow dimension in the bash 1 liner

### ISSUE THREAD

**Issue by calvinx408** [signalfx/signalfx-collectd-installer#32]
need options to allow a object of dimensions to be added .

**Comment by calvinx408** [comment]
never mind. it's in your bash script, but not in the readme:
```
-D 'sfxdim_<key>=<value>[&sfxdim_<key>=<value>]
```

**Comment by molner** [comment]
Thanks for bringing this to our attention, @calvinx408. We'll make sure the README gets updated appropriately.
